rest:
  timeout: 5 #Timeout des requêtes REST en secondes
info:
  app:
    name: ${project.name}
    description: ${project.description}
    artifactId: ${project.artifactId}
    version: ${project.version}
management:
  context-path: /manage
spring:
  data:
    mongodb:
      uri: mongodb://localhost/mfm